<?php

/**
 * @file
 * Main extension file for the 'misc' extension.
 */

/**
 * Implements hook_extension_EXTENSION_registry_alter().
 */
function aura_extension_misc_theme_registry_alter(&$registry) {
}

/**
 * Implements hook_extension_EXTENSION_preproces_page().
 */
function aura_extension_misc_preprocess_page(&$variables) {

}

/**
 * Implements hook_extension_EXTENSION_preproces_region().
 */
function aura_extension_misc_preprocess_region(&$variables) {

}
