<?php
// $id
/**
 * Options used in select form elements
 */

 function swiper_slider_transitions(){
	 return array(
		 'fade-in' => t('Fade in'),
		 'slide-top' => t('Slide in top'),
		 'slide-right' => t('Slide in right'),
		 'slide-bottom' => t('Slide in bottom'),
		 'slide-left' => t('Slide in left'),
		 'slide-scale' => t('Scale'),
		 'flip-x' => t('flip horizontally'),
		 'flip-y' => t('flip vertically'),
	 );
 }