name = Aura fullwidth layout
description = A Layout that has full width content wrapper and is good for building custom front page.
preview = preview.png
template = aura-full-layout

; Regions
regions[topbar]        = Top bar
regions[header]         = Header
regions[sub_menu]       = Sub Menu
regions[slider]         = Slider
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content_top]		= Content Top
regions[node_top]				= Node Top
regions[content]        = Content
regions[node_bottom]    = Node Bottom
regions[content_bottom]		= Content Bottom
regions[footer]         = Footer
regions[sub_footer]     = Sub footer

; Stylesheets
stylesheets[all][] = css/layouts/aura-full/aura-full-layout.css
