name = Aura Default
description = A 3 column layout with a prominent slider region.
preview = preview.png
template = aura-default-layout

; Regions
regions[topbar]        = Top bar
regions[header]         = Header
regions[sub_menu]       = Sub Menu
regions[slider]         = Slider
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content_top]		= Content Top
regions[node_top]				= Node Top
regions[content]        = Content
regions[node_bottom]    = Node Bottom
regions[content_bottom]		= Content Bottom
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[sub_footer]     = Sub footer

; Stylesheets
stylesheets[all][] = css/layouts/aura-default/aura-default-layout.min.css
